version: '3.8'
services:
  postgres:
    build:
      dockerfile: Dockerfile.postgres
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  pyway:
    build:
      dockerfile: Dockerfile.pyway
    environment:
      - PYWAY_CONFIG_FILE=/pyway/.pyway.conf
    depends_on:
      - postgres
