services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.db.dev
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  pyway:
    image: python:3.10
    volumes:
      - ./migrations:/pyway/migrations
      - ./.pyway.conf:/pyway/.pyway.conf
    environment:
    # check the pyway documentation for more info -- it may be safer to also define 
    # sensitive info as env vars from .env files and not include them in the .pyway.conf file
      - PYWAY_CONFIG_FILE=/pyway/.pyway.conf
    command: /bin/sh -c "pip install pyway && pyway info &&  tail -f /dev/null"
    depends_on:
      - postgres
